main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('courses/', CoursesListView.as_view(), name='courses'),
    path('category/<int:category_id>/', category, name='category'),
    path('course/<int:course_id>/', course, name='course'),
    path('lesson/<int:lesson_id>/', lesson, name='lesson'),
    path('check/', check_repository, name='check'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification'),
    path('repl/<str:repl_name>/<int:lesson_pk>/', repl_page, name='repl'),
    path('search/', search, name='search'),
    path('add_course_to_favorite/', add_course_to_favorite, name = 'add_course_to_favorite'),
    path('logout/', logout_user, name = 'logout'),
    path('about/', About.as_view(), name = 'about-us'),
    path('vacansy/', VacansyListView.as_view(), name = 'vacansy-list'),
    path('vacansy/<int:pk>/', VacansyDetailView.as_view(), name = 'vacansy'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField(max_length = 255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Direction(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    title = models.CharField(max_length = 255)
    photo = models.ImageField(upload_to='static/photo/direction')
    description = models.TextField()

    def __str__(self):
        return self.title


class Course(models.Model):
    direction = models.ForeignKey(Direction, on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='static/photo/course')
    description = models.TextField()
    duration = models.CharField(max_length = 10)
    language = models.CharField(max_length = 15)
    author = models.CharField(max_length = 255)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    duration = models.CharField(max_length=10)
    link = models.CharField(max_length = 355, default = '')
    repl_name = models.CharField(max_length = 255, default = '')


    def has_taskforlesson(self):
        if self.taskforlesson:
            return True
        else:
            return False

    def __str__(self):
        return self.title


class TaskForLesson(models.Model):
    lesson = models.OneToOneField(Lesson, on_delete = models.CASCADE)

    def __str__(self):
        return 'Задание урока ' + str(self.lesson)


class FileOfTask(models.Model):
    task = models.ForeignKey(TaskForLesson, on_delete = models.CASCADE)
    name = models.CharField(max_length = 255)
    description = models.TextField(default = '')

    def __str__(self):
        return 'Файл {} к заданию {}'.format(str(self.name), str(self.task))


class Notification(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    title = models.CharField(max_length = 255)
    content = models.TextField()
    is_viewed = models.BooleanField(default = False)

    def __str__(self):
        return "Уведомление '{}' пользователю {}".format(self.title, self.user)



class Vacansy(models.Model):
    title = models.CharField(max_length = 255)
    company = models.CharField(max_length = 255)
    date = models.DateField(auto_now = True)
    salary = models.CharField(max_length = 255)

    requirement_experience_set = [
        ('no', 'Не требуется / Не важно'),
        ('1-3', 'От 1 года до 3-х лет'),
        ('3-6', 'от 3-х лет до 6 лет'),
        ('6-10', 'от 6 лет до 10 лет'),
        ('10+', 'от 10 лет')
    ]
    requirement_experience = models.CharField(max_length = 255, choices=requirement_experience_set)

    work_mode_set = [
        ('full', 'Полный день'),
        ('part', 'Частичная занятость'),
        ('project', 'Проект/Разовая работа'),
        ('internship', 'Стажировка')
    ]
    work_mode = models.CharField(max_length = 255, choices = work_mode_set)

    description = models.TextField()

    def __str__(self):
        return f'{self.title}'

    def short_description(self):
        return str(self.description)[:100]


class VacansyRequirement(models.Model):
    title = models.CharField(max_length = 255)
    vacansy = models.ForeignKey(Vacansy, on_delete = models.CASCADE)


class VacansyResponsibility(models.Model):
    title = models.CharField(max_length = 255)
    vacansy = models.ForeignKey(Vacansy, on_delete = models.CASCADE)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView, TemplateView

from django.contrib.auth import authenticate, login, logout

from django.core.exceptions import ValidationError

from user_profile.forms import *
from .models import *

from .checking_git import check


def home(request, login_form = LoginForm, registration_form = RegistrationForm):
    return render(request, 'new/main.html', {'login_form': login_form, 'registration_form': registration_form})


def category(request, category_id):
    category = Category.objects.get(pk = category_id)
    courses = Course.objects.filter(direction__category = category)

    return render(request, 'new/courses.html', {'courses': courses, 'login_form': LoginForm, 'registration_form': RegistrationForm})


def course(request, course_id):
    course = Course.objects.get(pk = course_id)
    lessons = Lesson.objects.filter(course = course)

    response = render(request, 'new/lessons.html', {'lessons': lessons, 'login_form': LoginForm, 'registration_form': RegistrationForm})

    try:
        user = User.objects.get(username = request.user)
        user.usercourses.add_last_course(course)
    except Exception as e:
        pass

    return response


def lesson(request, lesson_id):
    lesson = Lesson.objects.get(pk = lesson_id)

    return render(request, 'new/insidecourses.html', {'lesson': lesson, 'login_form': LoginForm, 'registration_form': RegistrationForm})


def check_repository(request):
    git_repository = request.GET.get('git')

    lesson_name = request.GET.get('ln')
    lesson = Lesson.objects.get(title = lesson_name)

    list_of_files =  []

    for file in lesson.taskforlesson.fileoftask_set.all():
        list_of_files += file.name

    in_files, not_files = check(git_repository, list_of_files )

    content_text = 'Мы проверили ваше задание к уроку {}.<br>Результаты:<br>'.format(lesson)

    for in_file in in_files:
        content_text += '{} - Успех<br>'.format(in_file)

    for not_file in not_files:
        content_text += '{} - Провал<br>'.format(not_file)

    notification = Notification.objects.create(user = request.user, 
                                                title = 'Проверка задания {}'.format(lesson.taskforlesson),
                                                content = content_text)

    notification.save()

    return redirect('notifications')


class NotificationListView(ListView):

    model = Notification
    template_name = 'new/notifications.html'

    def get_queryset(self):
        qs = super().get_queryset()
        user_notifications = qs.filter(user = self.request.user).order_by('-pk')
        return user_notifications


class NotificationDetailView(DetailView):

    model = Notification
    template_name = 'new/notification_view.html'

    def get_queryset(self):
        qs = super().get_queryset()
        obj = qs.get(pk = self.kwargs['pk'])
        obj.is_viewed = True
        obj.save()
        return qs


def repl_page(request, repl_name, lesson_pk):
    lesson = Lesson.objects.get(pk = lesson_pk)
    tasks = lesson.taskforlesson.fileoftask_set.all()
    return render(request, 'new/task_repl.html', {'repl_name': repl_name, 'tasks': tasks})


def search(request):
    search_text = request.GET.get('search_text')
    courses = Course.objects.filter(title__contains = search_text)
    if len(courses) >= 1:
        return render(request, 'new/courses.html', {'courses': courses, 'is_search': True, 'message': 'Резуальтат поиска', 'login_form': LoginForm, 'registration_form': RegistrationForm})
    else:
        return render(request, 'new/courses.html', {'is_search': True, 'message': 'Результатов не найдено', 'login_form': LoginForm, 'registration_form': RegistrationForm})
    


class CoursesListView(ListView):
    model = Course
    order_by = '-pk'
    template_name = 'new/courses_list.html'



def add_course_to_favorite(request):
    user = User.objects.get(username = request.GET.get('user'))
    course = Course.objects.get(pk = request.GET.get('course_pk'))

    user.usercourses.add_my_course(course)

    return JsonResponse({'status': '200'})


def logout_user(request):
    logout(request)
    return redirect('home')


class About(TemplateView):
    template_name = 'new/about-us.html'



class VacansyListView(ListView):
    model = Vacansy
    template_name = 'new/jobs.html'

class VacansyDetailView(DetailView):
    model = Vacansy
    template_name = 'new/inside-job.html'

templates/new/about-us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static "css/about-us.css" %}">

	<section class="about-us">
		<div class="container">
			<div class="about-us__body">
				<div class="about-us__text">
					<div class="about-us__title">
						<h2>О нас</h2>
					</div>
					<div class="about-us__subtitle">
						<p>JIHC STUDY дает вам мгновенный доступ ко всем курсам - от <br>SMM до Mobile Development. Просто начни курс <br>который тебе по душе.</p>
					</div>
				</div>
				<div class="about-us__items_body">
					<div class="about-us__items">
						<div class="about-us__item">
							<img src="{% static "img/image 2.png" %}" alt="" class="item-img">
							<h4 class="item-title">Обучайся везде</h4>
							<p class="item-text">Наш курс работает на вашем <br>телефоне, ноутбуке и даже на ТВ.</p>
						</div>
						<div class="about-us__item">
							<img src="{% static "img/image 3.png" %}" alt="" class="item-img">
							<h4 class="item-title">Безлимитный, бесплатный</h4>
							<p class="item-text">Никакой рекламы. Никаких помех. <br>Только курсы.</p>
						</div>
						<div class="about-us__item">
							<img src="{% static "img/image 4.png" %}" alt="" class="item-img">
							<h4 class="item-title">Скачай и учись оффлайн</h4>
							<p class="item-text">Проходи наши курсы <br>даже если у тебя нету интернета</p>
						</div>
						<div class="about-us__item">
							<img src="{% static "img/image 5.png" %}" alt="" class="item-img">
							<h4 class="item-title">Качественно и удобно</h4>
							<p class="item-text">Готовься качественным урокам <br>и прокачай свой уровень</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/new/courses.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
	{% if not is_search %}
	<section class="bread">
		<div class="container">
			<div class="bread">
				<a href="{% url 'home' %}">Главная страница</a>
				<i class="fas fa-angle-right"></i>
				<a href="{% url 'category' courses.first.direction.category.pk %}">{{ courses.first.direction.category }}</a>
			</div>
		</div>
	</section>
	{% endif %}
	<section class="courses__web">
		<div class="container">
			<div class="courses__popular">
				<div class="courses__popular_title">
					<h2>{% if is_search %}{{ message }}{% else %}{{ courses.first.direction.category }}{% endif %}</h2>
				</div>
				<div class="courses__popular__items">
					{% for course in courses %}
					<div class="course__item">
						<div class="course__image">
							<img src="{{ course.photo.url }}" alt="" >
						</div>
						<div class="course__info">
							<div class="course__text">
								<div class="course__name">
									<h2>{{ course.title }}</h2>
									<h4>{{ course.direction }}</h4>
									<p>{{ course.description }}</p>
								</div>
							</div>
							<div class="course__about">
								<div class="course__contain">
									<p><i class="far fa-clock"></i>{{ course.duration }}</p>
									<p><i class="far fa-play-circle"></i>{{ course.lesson_set.count }} урок(ов)</p>
									<p><i class="fas fa-globe"></i>{{ course.language }}</p>
									<p><i class="far fa-user"></i>{{ course.author }}</p>
								</div>
								<div class="course__btn">
									<a href="{% url 'course' course.pk %}">Посмотреть</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>
	{% endblock %}

templates/new/courses_list.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
	<section class="courses__web">
		<div class="container">
			<div class="courses__popular">
				<div class="courses__popular_title">
					<h2>Курсы</h2>
				</div>
				<div class="courses__popular__items">
					{% for course in object_list %}
					<div class="course__item">
						<div class="course__image">
							<img src="{{ course.photo.url }}" alt="" width="100">
						</div>
						<div class="course__info">
							<div class="course__text">
								<div class="course__name">
									<h2>{{ course.title }}</h2>
									<h4>{{ course.direction }}</h4>
									<p>{{ course.description }}</p>
								</div>
							</div>
							<div class="course__about">
								<div class="course__contain">
									<p><i class="far fa-clock"></i>{{ course.duration }}</p>
									<p><i class="far fa-play-circle"></i>{{ course.lesson_set.count }} урок(ов)</p>
									<p><i class="fas fa-globe"></i>{{ course.language }}</p>
									<p><i class="far fa-user"></i>{{ course.author }}</p>
								</div>
								<div class="course__btn">
									<a href="{% url 'course' course.pk %}">Посмотреть</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>
	{% endblock %}

templates/new/inside-job.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- CONTENT -->
	<header class="inside__header">
		<div class="container">
			<section class="bread">
				<div class="bread">
					<a href="{% url 'home' %}">Главная страница</a>
					<i class="fas fa-angle-right"></i>
					<a href="{% url 'vacansy-list' %}">Вакансии</a>
					<i class="fas fa-angle-right"></i>
					<a href="{% url 'vacansy' object.pk %}">{{ object.title }}</a>
				</div>
			</section>
			<h2 class="inside__course-name">{{ object.title }}</h2>
			<p class="inside__course-subtitile color-white">{{ object.company }}</p>
			<div class="course__contain" style="display: flex; justify-content: flex-start; margin-top: 20px;">
				<p style="color: #FFDC4E;"><i class="far fa-clock"></i>{{ object.date }}</p>
				<p style="color: #FFDC4E;"> {{ object.salary }} KZT</p>
			</div>
		</div>
	</header>
	<div class="inside__info">
		<div class="container__2">
			<div class="inside__info_main" style="color: #6FFFE9">
				<p class="contain__text">Требуемый оыт работы: 	{{ object.get_requirement_experience_display }}</p>
				<p class="contain__text">График: {{ object.get_work_mode_display }}</p>
				<p class="contain__text">Requirements:</p>
				<ul style="margin-left: 20px;">
					{% for req in object.vacansyrequirement_set.all %}
					<li>{{ req.title }}</li>
					{% endfor %}
				</ul>
				<p class="contain__text">Responsibilities:</p>
				<ul style="margin-left: 20px;">
					{% for res in object.vacansyresponsibility_set.all %}
					<li>{{ res.title }}</li>
					{% endfor %}
				</ul>
				<div class="course__btn" >
						<a style="display: inline-block;  margin-top: 20px;" href="inside-job.html">Откликнуться</a>
				</div>
			</div>
		</div>
	</div>
	<section class="same-jobs">
		<div class="container">
			<div class="courses__popular">
				<div class="courses__popular_title">
					<h2>Похожие вакансии</h2>
				</div>
				<div class="courses__popular__items">
					<div class="course__item">
						<div class="course__info">
							<div class="course__text">
								<div class="course__name">
									<h2>UI/UX дизайнер</h2>
									<h4 class="color-white">ТОО UNION SERVICE COMPANY</h4>
									<p>Text max 100 words Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corporis, ipsa. Quos, provident. Eligendi quisquam est officiis facilis. Voluptatibus, incidunt architecto similique beatae repudiandae quibusdam dignissimos, in sed, est natus molestiae!</p>
								</div>
							</div>
							<div class="course__about" style="display: flex; justify-content: space-between;color: align-items: center;">
								<div class="course__contain">
									<p><i class="far fa-clock"></i>15.07.21</p>
									<p>₸ 150.000 - 300.000 KZT</p>
								</div>
								<div class="course__btn">
									<a href="inside-job.html">Откликнуться</a>
								</div>
							</div>
						</div>
					</div>
					<div class="course__item">
						<div class="course__info">
							<div class="course__text">
								<div class="course__name">
									<h2>Back-end разработчик</h2>
									<h4 class="color-white">ТОО Qazaq International Holding</h4>
									<p>Верстка сайта по разработанному дизайну. Адаптация сайта для разных носителей. Оптимизация работы сайта. Периодическое введение изменении, дополнении. Доработка и оптимизация...</p>
								</div>
							</div>
							<div class="course__about" style="display: flex; justify-content: space-between;color: align-items: center;">
								<div class="course__contain">
									<p><i class="far fa-clock"></i>15.07.21</p>
									<p>₸ 350.000 - 500.000 KZT</p>
								</div>
								<div class="course__btn">
									<a href="inside-job.html">Откликнуться</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
<!-- CONTENT -->

{% endblock %}

templates/new/insidecourses.html
{% extends 'base.html' %}
{% load static %}

        {% block content %}

			<header class="inside__header">
				<div class="container">
				<section class="bread">
					<div class="bread">
						<a href="{% url 'home' %}">Главная страница</a>
                        <i class="fas fa-angle-right"></i>
                        <a href="{% url 'category' lesson.course.direction.category.pk %}">{{ lesson.course.direction.category }}</a>
                        <i class="fas fa-angle-right"></i>
                        <a href="% url 'course' lesson.course.pk">{{ lesson.course }}</a>
                        <i class="fas fa-angle-right"></i>
                        <a href="% url 'lesson' lesson.pk">{{ lesson }}</a>
					</div>
				</section>
				<h2 class="inside__course-name">{{ lesson }}</h2>
				<p class="inside__course-subtitile">{{ lesson.course }}</p>
				</div>
			</header>
			<div class="inside__info">
				<div class="container__2">
					<div class="inside__info_main">
						<div class="course__contain">
							<div class="course__contain-text">
								<p><i class="far fa-clock"></i>{{ lesson.course.duration }}</p>
								<p><i class="far fa-play-circle"></i>{{ lesson.course.lesson_set.count }} урок(ов)</p>
								<p><i class="fas fa-globe"></i>{{ lesson.course.language }}</p>
								<p><i class="far fa-calendar-alt"></i> 01.02.2020</p>
								<p><i class="far fa-user"></i>{{ lesson.course.author }}</p>
							</div>
							<div class="course__contain-rating">
								<img src="{% static 'img/rating.png' %}" alt="">
							</div>
						</div>
						<p class="contain__text">{{ lesson.course.description }}</p>
					</div>
				</div>
			</div>
			<section class="video__player">
				<div class="container">
					<div class="video__player__main">
						<iframe width="760" height="515" src="{{ lesson.link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
					</div>
					<div class="video__player_btns">
						<a href="{% url 'repl' lesson.repl_name lesson.pk %}" class="download__course {% if lesson.has_taskforlesson %}{% else %}disabled{% endif %}">Открыть онлайн тренажер</a>
						<a onclick="addCourseToFavorite()" class="download__materials {% if user.is_authenticated %}{% else %}disabled{% endif %}">Добавить курс в 'Мои курсы'</a>
						<a href="#"><i class="fas fa-heart"></i></a>
						<a href="#"><i class="far fa-thumbs-up"></i></a>
						<a href="#"><i class="far fa-thumbs-down"></i></a>
					</div>
					<div class="validation__main">
				      <input type="text" name="git_link" id="git_link_input" class="git_link_input {% if lesson.has_taskforlesson %}{% else %}disabled{% endif %}" placeholder="git">
				      <button onclick="send_get_request_to_back()" class="validationCheck {% if lesson.has_taskforlesson %}{% else %}disabled{% endif %}">Проверить</button>
			     	</div>
				</div>

			</section>


			<script type="text/javascript">
				async function addCourseToFavorite() {
					let response = await fetch('/add_course_to_favorite/?user={{ request.user }}&course_pk={{ lesson.course.pk }}');

					if (response.ok) {
						let btn = document.querySelector('.download__materials');
						btn.textContent = "Добавлено в 'Мои курсы'";
						btn.style.backgroundColor = '#bf9d10'
					}
				}
			</script>

        {% endblock %}

templates/new/jobs.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- CONTENT -->
	<section class="bread">
		<div class="container">
			<div class="bread">
				<a href="#!">Главная страница</a>
				<i class="fas fa-angle-right"></i>
				<a href="#!">Вакансии</a>
			</div>
		</div>
	</section>
	<section class="courses__web">
		<div class="container">
			<div class="courses__popular">
				<div class="courses__popular_title">
					<h2>Вакансии</h2>
				</div>
				<div class="courses__popular__items">
					{% for vacansy in object_list %}
					<div class="course__item">
						<div class="course__info">
							<div class="course__text">
								<div class="course__name">
									<h2>{{ vacansy.title }}</h2>
									<h4 class="color-white">{{ vacansy.company }}</h4>
									<p>{{ vacansy.short_description }}</p>
								</div>
							</div>
							<div class="course__about" style="display: flex; justify-content: space-between;color: align-items: center;">
								<div class="course__contain">
									<p><i class="far fa-clock"></i>{{ vacansy.date }}</p>
									<p> {{ vacansy.salary }} KZT</p>
								</div>
								<div class="course__btn">
									<a href="{% url 'vacansy' vacansy.pk %}">Откликнуться</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>
<!-- CONTENT -->

{% endblock %}

templates/new/lessons.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
	<section class="bread">
		<div class="container">
			<div class="bread">
				<a href="{% url 'home' %}">Главная страница</a>
				<i class="fas fa-angle-right"></i>
				<a href="{% url 'category' lessons.first.course.direction.category.pk %}">{{ lessons.first.course.direction.category }}</a>
                <i class="fas fa-angle-right"></i>
				<a href="{% url 'course' lessons.first.course.pk %}">{{ lessons.first.course }}</a>
			</div>
		</div>
	</section>
	<section class="courses__web">
		<div class="container">
			<div class="courses__popular">
				<div class="courses__popular_title">
					<h2>{{ lessons.first.course }}</h2>
				</div>
				<div class="courses__popular__items">
					{% for lesson in lessons %}
					<div class="course__item">
						<div class="course__info">
							<div class="course__text">
								<div class="course__name">
									<h2>{{ lesson.title }}</h2>
									<h4>{{ lesson.direction }}</h4>
									<p>{{ lesson.description }}</p>
								</div>
							</div>
							<div class="course__about">
								<div class="course__contain">
									<p><i class="far fa-clock"></i>{{ lesson.duration }}</p>
								</div>
								<div class="course__btn">
									<a href="{% url 'lesson' lesson.pk %}">Посмотреть</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>
	{% endblock %}

templates/new/log in.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/login-register.css' %}">
	<title>Login</title>
</head>
<body>
	<section class="reg-form">
		<div class="container">
			<div class="reg-form__body">
				<div class="reg-form__title">
					<a href="index.html"><span class="reg-form__title-1">JIHC</span>Study</a>
				</div>
				<div class="register_container">
					<form class="register_panel active" data-index="0" method="post" action="{% url 'login' %}">

						{% for error in login_form.non_field_errors %}
					        <div class="alert alert-danger">
					            <strong>{{ error|escape }}</strong>
					        </div>
					    {% endfor %}

						{% csrf_token %}

						{% for field in login_form %}

							<label for="{{ field.id_for_label }}" class="register_labelname">{{ field.label }}</label>
							{{ field }}

							{% if field.errors %}

								{% for error in field.errors %}
									<p>{{ error }}</p>
								{% endfor %}
								
							{% endif %}
							
						{% endfor %}

						<input class="register_btn" type="submit" value="Войти" />
						<a class="register_linktext" href="#!">By signing up to create an account I accept iCourses’ Terms of Use and Privacy Policy</a>
					</form>
				</div>
			</div>
		</div>
	</section>
</body>
</html>

templates/new/main.html
{% extends 'base.html' %}
{% load static %}

        {% block content %}
        <!--HEADER START-->
          <header class="header">
          <div class="container">
            <div class="header_content">
              <div class="header_left">
                <h1>Онлайн курсы <br> в одном месте</h1>
                <p>Развивайте свою карьеру. Получите доступ <br> к нашим высококачественным онлайн-курсам</p>
                <div class="header_register_registration-border">
                  <a class="header_register_registration" href="{% url 'courses' %}">К курсам</a>
                </div>
              </div>
              <div class="header_right">
                <img src="{% static 'img/header_bq2.png' %}" alt="">
              </div>
            </div>
          </div>
          </header>
    <!--HEADER END-->

        <!--HEADER COURSERS START-->
        <section class="header_coursers">
          <div class="container">
            <div class="header_coursers_title">
              Достигай своих целей с JIHC-Study
            </div>
            <div class="header_coursers-content">
              <div class="header_coursers-item">
                  <img src="{% static 'img/courseicon.svg' %}" alt="">
                  <h3>Учись новейшим <br> навыкам</h3>
                  <p>как Маркетинг,<br> Web-дизайн, Python и <br> многое другое.</p>
              </div>
              <div class="header_coursers-item">
                  <img src="{% static 'img/teachericon.svg' %}" alt="">
                  <h3>Подготовься <br> к карьере</h3>
                  <p>в высоко <br> востребованных <br> областях, как IT, SММ.</p>
              </div>
              <div class="header_coursers-item">
                  <img src="{% static 'img/Diplomicon.svg' %}" alt="">
                  <h3>Получи<br> сертификат</h3>
                  <p>из лучших учителей <br> в области IT и <br> многого другого.</p>
              </div>
              <div class="header_coursers-item">
                  <img src="{% static 'img/organizationicon.svg' %}" alt="">
                  <h3>Повышайте <br> квалификацию </h3>
                  <p>с программами <br> обучения и развития <br> по требованию</p>
              </div>
            </div>
          </div>
        </section>
        <!--HEADER COURSERS END-->
        {% endblock %}

templates/new/task_repl.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/task_repl.css' %}">

	<section class="sandbox">
		<div class="sandbox__body">
			<div class="task__list">
				<div class="task__wrap">
					{% for task in tasks %}
					<div class="task__item">
						<input class="task__input" type="checkbox" id="task_{{ task.pk }}">
						<label class="task__title" for="task_{{ task.pk }}">{{ task.name }}</label>
						<div class="task__text">
							<p>{{ task.description }}</p>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
			<div class="sandbox__main">
				<div class="container__ide">
					<iframe class="ide" src="https://repl.it/@MarlenShifu/{{ repl_name }}?lite=true" scrolling="no" frameborder="no" allowtransparency="true" allowfullscreen="true" sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-modals"></iframe>
				</div>
			</div>
		</div>
	</section>
{% endblock %}